"""create profiles and dashboard_items

Revision ID: 9cd63fe5b46e
Revises: 
Create Date: 2026-09-07 20:54:52.476559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cd63fe5b46e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('size_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='reviewing', nullable=False),
    sa.Column('list_price', sa.BigInteger(), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('dong', sa.String(length=20), nullable=True),
    sa.Column('ho', sa.String(length=20), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=True),
    sa.Column('interior', sa.String(length=50), nullable=True),
    sa.Column('memo', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dashboard_items_user_id', 'dashboard_items', ['user_id'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=30), nullable=True),
    sa.Column('age_group', sa.String(length=10), nullable=True),
    sa.Column('purposes', sa.ARRAY(sa.String(length=30)), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # --- 여기부터는 손으로 추가한 외래키 ---
    # app/db_models_user.py 에 ForeignKey를 선언하지 않은 이유는 그 파일 상단 주석 참고.

    # profiles.id -> auth.users.id
    # 회원이 탈퇴해서 auth.users에서 사라지면 프로필도 같이 삭제되도록 CASCADE.
    op.create_foreign_key(
        "fk_profiles_auth_users",
        source_table="profiles", referent_table="users",
        local_cols=["id"], remote_cols=["id"],
        referent_schema="auth", ondelete="CASCADE",
    )

    # dashboard_items.user_id -> profiles.id
    op.create_foreign_key(
        "fk_dashboard_items_user",
        source_table="dashboard_items", referent_table="profiles",
        local_cols=["user_id"], remote_cols=["id"],
        ondelete="CASCADE",
    )

    # TODO: dashboard_items.size_id -> size_master.id 외래키는 아직 걸지 않는다.
    #       B의 실거래 테이블이 이 DB로 이관된 뒤에 별도 마이그레이션으로 추가할 것.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_dashboard_items_user', 'dashboard_items', type_='foreignkey')
    op.drop_constraint('fk_profiles_auth_users', 'profiles', type_='foreignkey')
    op.drop_index('ix_dashboard_items_user_id', table_name='dashboard_items')
    op.drop_table('dashboard_items')
    op.drop_table('profiles')
    # ### end Alembic commands ###
